namespace RAG_RBAC.Models;

/// <summary>
/// Request payload for ingesting a document into the vector store.
/// The document will be embedded and stored in Pinecone with RBAC metadata.
/// </summary>
/// <param name="Title">The document title displayed in search results.</param>
/// <param name="Content">The full text content to be embedded and indexed.</param>
/// <param name="Source">The origin system (e.g., "HR Portal", "Engineering Wiki").</param>
/// <param name="MinimumAccessRole">
/// The minimum <see cref="AppRole"/> required to access this document. Defaults to "Intern" (public).
/// </param>
/// <param name="Department">The organizational department tag. Defaults to "General".</param>
public record IngestRequest(
    string Title,
    string Content,
    string Source,
    string MinimumAccessRole = "Intern",
    string Department = "General"
);

/// <summary>
/// Request payload for querying the RAG pipeline with RBAC enforcement.
/// </summary>
/// <param name="UserId">The authenticated user's ID, used to determine access level via <see cref="RAG_RBAC.Services.RbacService"/>.</param>
/// <param name="Question">The natural language question to answer using retrieved context.</param>
/// <param name="TopK">The maximum number of relevant document chunks to retrieve. Defaults to 3.</param>
public record QueryRequest(
    string UserId,
    string Question,
    int TopK = 3
);

/// <summary>
/// Response payload containing the LLM-generated answer and the source documents used.
/// </summary>
/// <param name="Answer">The grounded answer generated by GPT-4o based on retrieved context.</param>
/// <param name="Sources">The list of document chunks retrieved and used as context for the answer.</param>
/// <param name="UserRole">The querying user's role level (e.g., "Developer", "Manager").</param>
/// <param name="DocumentsSearched">The total number of RBAC-filtered documents used as context.</param>
public record QueryResponse(
    string Answer,
    List<RetrievedChunk> Sources,
    string UserRole,
    int DocumentsSearched
);

/// <summary>
/// Represents a single document chunk retrieved from the vector store during a RAG query.
/// </summary>
/// <param name="Title">The title of the retrieved document.</param>
/// <param name="Source">The origin system of the document.</param>
/// <param name="Department">The department associated with the document.</param>
/// <param name="RelevanceScore">The cosine similarity score (0.0 to 1.0) indicating relevance to the query.</param>
public record RetrievedChunk(
    string Title,
    string Source,
    string Department,
    double RelevanceScore
);
