using Microsoft.Extensions.VectorData;

namespace RAG_RBAC.Models;

/// <summary>
/// Represents a document chunk stored in the Pinecone vector database.
/// Each record contains the document text, its vector embedding, and
/// RBAC metadata used for role-based filtering at query time.
/// </summary>
/// <remarks>
/// The <see cref="MinimumAccessRole"/> metadata field is the key to RBAC enforcement.
/// During vector search, documents are filtered so that users only retrieve
/// content they are authorized to access based on their role level.
/// Embedding dimensions (1536) correspond to the OpenAI text-embedding-ada-002 model.
/// </remarks>
public class RagDocument
{
    /// <summary>Gets or sets the unique document identifier (GUID) used as the Pinecone vector ID.</summary>
    [VectorStoreRecordKey]
    public string Id { get; set; } = Guid.NewGuid().ToString();

    /// <summary>Gets or sets the document title. Filterable in Pinecone for metadata-based queries.</summary>
    [VectorStoreRecordData(IsFilterable = true)]
    public string Title { get; set; } = string.Empty;

    /// <summary>Gets or sets the full text content of the document, used for embedding generation and LLM context.</summary>
    [VectorStoreRecordData]
    public string Content { get; set; } = string.Empty;

    /// <summary>Gets or sets the origin system of the document (e.g., "HR Portal", "Engineering Wiki").</summary>
    [VectorStoreRecordData(IsFilterable = true)]
    public string Source { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the minimum role level required to access this document.
    /// Stored as a string in Pinecone metadata to enable RBAC filtering.
    /// </summary>
    /// <remarks>
    /// Valid values correspond to <see cref="AppRole"/> names: "Intern", "Developer", "Manager", "Director", "Admin".
    /// A value of "Manager" means only users with Manager, Director, or Admin roles can access this document.
    /// Defaults to "Intern" (publicly accessible to all authenticated users).
    /// </remarks>
    [VectorStoreRecordData(IsFilterable = true)]
    public string MinimumAccessRole { get; set; } = AppRole.Intern.ToString();

    /// <summary>Gets or sets the department tag for organizational filtering (e.g., "Engineering", "Finance").</summary>
    [VectorStoreRecordData(IsFilterable = true)]
    public string Department { get; set; } = "General";

    /// <summary>
    /// Gets or sets the vector embedding generated by the text-embedding-ada-002 model.
    /// Used for cosine similarity search in Pinecone.
    /// </summary>
    [VectorStoreRecordVector(Dimensions: 1536, DistanceFunction.CosineSimilarity)]
    public ReadOnlyMemory<float>? Embedding { get; set; }
}
